// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzzgvOanYI3hbG1WgiDRS70Hg5to8WF_s',
    appId: '1:278372965710:web:42e052e66b3f5b3039121f',
    messagingSenderId: '278372965710',
    projectId: 'fonoplay-2022',
    authDomain: 'fonoplay-2022.firebaseapp.com',
    storageBucket: 'fonoplay-2022.appspot.com',
    measurementId: 'G-MDQK24PEDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5bLl2piFee4gOv5ddSe4BdnlEHRYQAVo',
    appId: '1:278372965710:android:b9d74559cef1c72d39121f',
    messagingSenderId: '278372965710',
    projectId: 'fonoplay-2022',
    storageBucket: 'fonoplay-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBn-3mnBxH4nNPulSZOhzljxJjmwHpbI',
    appId: '1:278372965710:ios:6f19b3e7c443275a39121f',
    messagingSenderId: '278372965710',
    projectId: 'fonoplay-2022',
    storageBucket: 'fonoplay-2022.appspot.com',
    androidClientId: '278372965710-0luh0vlu9ijnaf0ms89c65au23pp3278.apps.googleusercontent.com',
    iosClientId: '278372965710-h82dg7j54egjlthi2rjl0rrggo8549gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fonoplay',
  );
}
